server:
  port: 8099

spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/task
    username: postgres
    password: postgre
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect