server:
  port: 8099

spring:

  security:
    user:
      name: admin
      password: password
      roles: ADMIN

  datasource:
    url: jdbc:postgresql://localhost:5432/task
    username: postgres
    password: postgre
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    org.springframework.security: DEBUG